version: '3'

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    depends_on:
      - docker
    networks:
      jenkins:
        aliases:
          - jenkins
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
  
  docker:
    container_name: dind
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
      VIRTUAL_PORT: 2376
    ports:
      - "2376:2376"
      - "3000:3000"
      - "5000:5000"
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker
    restart: always
  
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    restart: always
    user: root
    environment: 
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"
    depends_on:
      - docker
    networks:
      jenkins:
        aliases:
          - jenkins

  webapp:
    container_name: webapp
    build: ./webapp
    ports:
      - "80:80"

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins:
    name: jenkins
    driver: bridge
